### ISSUE TITLE
Introduce support for prefers-color-scheme

### ISSUE THREAD

**Issue by admturner** [washingtonstateuniversity/hrs.wsu.edu#111]
**Describe the solution you'd like**

Would like to provide both a light and a dark version of the theme -- using the light/dark WSU design system options -- based on user preference using the `prefers-color-scheme` media query.

- [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
- [Can I Use support table](https://caniuse.com/#search=prefers-color-scheme)
- [CSS Tricks article](https://css-tricks.com/dark-modes-with-css/)

Sample CSS using CSS variables and the `prefers-color-scheme` media query:

```css
:root {
	--primary-color: #ccc;
}

@media screen and (prefers-color-scheme: dark) {
	:root {
		--primary-color: #222;
	}
}

body {
	background-color: var(--primary-color);
}
```
